<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="exoCar" nsURI="com.dps.fr.exoCar" nsPrefix="exoCar">
  <eClassifiers xsi:type="ecore:EClass" name="Car">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matriculationNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" unsettable="true">
      <eAnnotations source="teneo.jpa" references="#//Car/matriculationNumber/%teneo.jpa%">
        <details key="value" value="@Id"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mileage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuelCapacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brend" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuelConsumption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentFuelLevel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuelType" lowerBound="1"
        eType="#//GazType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" eType="#//Person"
        eOpposite="#//Person/cars"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" lowerBound="1" eType="#//ColorsType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cars" upperBound="-1" eType="#//Car"
        eOpposite="#//Car/person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GazType">
    <eLiterals name="GASOLINE"/>
    <eLiterals name="DIESEL"/>
    <eLiterals name="GPL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ColorsType">
    <eLiterals name="BLACK"/>
    <eLiterals name="GREEN"/>
    <eLiterals name="YELLOW"/>
    <eLiterals name="WHITE"/>
    <eLiterals name="RED"/>
  </eClassifiers>
</ecore:EPackage>
